name: video-downloader
license: GPL-3.0+
grade: stable
adopt-info: video-downloader

base: core18
confinement: strict

apps:
  video-downloader:
    command: usr/bin/video-downloader
    extensions: [gnome-3-28]
    plugs:
      - gsettings
      - home
      - network
    slots:
      - dbus-daemon
    common-id: com.github.unrud.VideoDownloader
    desktop: usr/share/applications/com.github.unrud.VideoDownloader.desktop

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.github.unrud.VideoDownloader

environment:
  # WORKAROUND: .../pulseaudio subdirectory is missing from library path
  LD_LIBRARY_PATH: "${SNAP}/usr/lib/aarch64-linux-gnu/pulseaudio:${SNAP}/usr/lib/arm-linux-gnueabihf/pulseaudio:${SNAP}/usr/lib/i386-linux-gnu/pulseaudio:${SNAP}/usr/lib/powerpc64le-linux-gnu/pulseaudio:${SNAP}/usr/lib/s390x-linux-gnu/pulseaudio:${SNAP}/usr/lib/x86_64-linux-gnu/pulseaudio"

parts:
  youtube-dl:
    plugin: python
    source: https://github.com/ytdl-org/youtube-dl/archive/2020.06.06.tar.gz
    source-checksum: sha256/9b29c376fdb4ebeda084ade898a678c9437b791bf7e8c6d71aef9285d376c722
    python-packages:
      - pyxattr
    stage-packages:
      # Missing optional dependencies atomicparsley, mpv, phantomjs and rtmpdump
      - ffmpeg
      - libslang2  # required by ffmpeg
      - freeglut3
      - libglu1-mesa
    override-build: |
      snapcraftctl build
      # WORKAROUND: Use correct python version
      sed -e '1c#!/usr/bin/env python3' -i "${SNAPCRAFT_PART_INSTALL}/bin/youtube-dl"

  pygobject:
    plugin: python
    python-packages:
      - pycairo
      - PyGObject
    build-packages:
      - libgirepository1.0-dev
      - libcairo2-dev
      - python3-dev
    stage-packages:
      - gir1.2-gtk-3.0

  video-downloader:
    plugin: meson
    source: .
    source-type: git
    # WORKAROUND: Fake installation location, to find dependencies when running
    meson-parameters: [--prefix=/snap/video-downloader/current/usr]
    build-packages:
      - gettext
      - librsvg2-bin
    stage-packages:
      - xdg-user-dirs
    override-pull: |
      snapcraftctl pull
      # WORKAROUND: Point icon to the correct location
      sed -e 's|Icon=com.github.unrud.VideoDownloader|Icon=/usr/share/icons/hicolor/scalable/apps/com.github.unrud.VideoDownloader.svg|' -i data/com.github.unrud.VideoDownloader.desktop.in
    override-build: |
      snapcraftctl build
      # WORKAROUND: Version is not extracted from AppStream
      snapcraftctl set-version "$(sed -n 's/^\s*VERSION\s*=\s*["'\'']\([^"'\'']*\)["'\''].*/\1/p' "${SNAPCRAFT_PART_INSTALL}/snap/video-downloader/current/usr/bin/video-downloader")"
      # WORKAROUND: Use correct python version
      sed -e '1c#!/usr/bin/env python3' -i "${SNAPCRAFT_PART_INSTALL}/snap/video-downloader/current/usr/bin/video-downloader"
    organize:
      snap/video-downloader/current/usr: usr
    parse-info: [usr/share/metainfo/com.github.unrud.VideoDownloader.appdata.xml]

  compile-schemas:
    plugin: nil
    after: [youtube-dl, pygobject, video-downloader]
    override-prime: |
      snapcraftctl prime
      glib-compile-schemas usr/share/glib-2.0/schemas
