# Build by running "snapcraft".

# WARNING:
# Snapcraft uses caching for already build steps but it's buggy and can cause strange problems.
# Clean the cache by running "snapcraft clean".

name: video-downloader
license: GPL-3.0+
grade: stable
adopt-info: video-downloader

base: core18
confinement: strict

apps:
  video-downloader:
    command: usr/bin/video-downloader
    # HINT: Adds plugs and changes environment variables when building and running
    # WARNING: Libraries bundled with the extension are incompatible with libraries from packages
    extensions: [gnome-3-34]
    # WORKAROUND: Use (correct version of) PyGObject from Gnome Extension
    # WARNING: There is another version of PyGObject in usr/lib/python3/dist-packages that crashes with SEGFAULT
    environment:
      PYTHONPATH: $SNAP_DESKTOP_RUNTIME/usr/lib/python3.6/site-packages
    plugs:
      - home
      - network
    slots:
      - dbus-daemon
    common-id: com.github.unrud.VideoDownloader
    desktop: usr/share/applications/com.github.unrud.VideoDownloader.desktop

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.github.unrud.VideoDownloader

# WARNING:
# There are multiple versions of Python. The paths are different when building
# and running the Snap. Each version has different search paths for modules.
#   - Base Snap: /usr/bin/python3
#   - Gnome Extension:
#       - Build: /snap/gnome-VERSION-sdk/current/usr/bin/python3
#       - Run: /snap/video-downloader/VERSION/gnome-platform/usr/bin/python3
#   - This Snap (Automatically installed by a plugin or as a dependency of some package)
#       - Build: /root/stage/usr/bin/python3
#       - Run: /snap/video-downloader/VERSION/usr/bin/python3

# WARNING:
# The environment (PATH, LD_LIBRARY_PATH etc.) prefers different paths:
#   - Build: Gnome extension; This Snap; Base Snap
#   - Run: This Snap; Base Snap; Gnome extension

# WARNING:
# Python must be bundled with this Snap or building fails with:
#     Failed to generate snap metadata: The specified command '/usr/bin/python3 $SNAP/usr/bin/video-downloader' defined in the app 'video-downloader' does not match the pattern expected by snapd.

parts:
  # WORKAROUND: Building Gnome extension fails because errno.h is missing
  gnome-extension-fix:
    plugin: nil
    build-packages:
      - libc6-dev

  libhandy:
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/libhandy/-/archive/1.4.0/libhandy-1.4.0.tar.bz2
    source-checksum: sha256/4c48a426db5afbfc0014b1ea0c75557cb7b5207406363a768a9c370e047e3420
    meson-parameters:
      # WORKAROUND: Install to /usr instead of /usr/local because it's not in search paths
      - --prefix=/usr
      - -Dexamples=false
      - -Dglade_catalog=disabled
      - -Dtests=false
      - -Dvapi=false
    stage:
      - -usr/include

  ffmpeg:
    # WORKAROUND:
    # Build from source because the ffmpeg package installs libraries as dependencies
    # that conflict with the Gnome extension
    plugin: autotools
    source: https://ffmpeg.org/releases/ffmpeg-4.4.1.tar.xz
    source-checksum: sha256/eadbad9e9ab30b25f5520fbfde99fae4a92a1ae3c0257a8d68569a4651e30e02
    configflags:
      # WORKAROUND: Install to /usr instead of /usr/local because it's not in search paths
      - --prefix=/usr
      - --disable-debug
      - --disable-doc
      - --disable-static
      - --enable-gpl
      - --enable-shared
      - --disable-ffplay
      - --disable-devices
      - --enable-gnutls
      - --enable-libmp3lame
      - --enable-libvorbis
    build-packages:
      - nasm
      - libgnutls28-dev
      - libmp3lame-dev
      - libvorbis-dev
    stage-packages:
      - libmp3lame0
    stage:
      - -usr/include

  yt-dlp:
    # Missing optional dependencies atomicparsley, mpv, phantomjs and rtmpdump
    after: [ffmpeg]
    plugin: python
    source: https://github.com/yt-dlp/yt-dlp/archive/refs/tags/2021.10.22.tar.gz
    source-checksum: sha256/63f267cb0f2e9d18afc8e51267be2a13ce60030eab7c04b25b94d6b90d2ba6d3
    python-packages:
      - pyxattr==0.7.2

  video-downloader:
    after: [libhandy, yt-dlp]
    plugin: meson
    source: .
    source-type: git
    # WORKAROUND: Fake installation location to find dependencies at runtime
    meson-parameters: [--prefix=/snap/video-downloader/current/usr]
    build-packages:
      - gettext
      - appstream
      - librsvg2-bin
    stage-packages:
      - xdg-user-dirs
    override-pull: |
      snapcraftctl pull
      # WORKAROUND: Point icon directly to SVG otherwise snapcraft automatically chooses lowest resolution
      sed -e 's|Icon=com.github.unrud.VideoDownloader|Icon=/usr/share/icons/hicolor/scalable/apps/com.github.unrud.VideoDownloader.svg|' -i data/com.github.unrud.VideoDownloader.desktop.in
    override-build: |
      snapcraftctl build
      # WORKAROUND: Use python from search path, the path detected by meson doesn't exist when running the Snap
      sed -e '1c#!/usr/bin/env python3' -i "${SNAPCRAFT_PART_INSTALL}/snap/video-downloader/current/usr/bin/video-downloader"
    organize:
      # WORKAROUND: Move files from fake installation location to actual target
      snap/video-downloader/current/usr: usr
    parse-info: [usr/share/metainfo/com.github.unrud.VideoDownloader.metainfo.xml]
