name: video-downloader
# WORKAROUND: Snapcraft doesn't accept GPL-3.0-or-later
license: GPL-3.0
grade: stable
adopt-info: video-downloader

base: core18
confinement: strict

apps:
  video-downloader:
    command: usr/bin/video-downloader
    extensions: [gnome-3-28]
    plugs:
      - gsettings
      - home
      - network
    slots:
      - dbus-daemon
    common-id: com.github.unrud.VideoDownloader
    desktop: usr/share/applications/com.github.unrud.VideoDownloader.desktop
  youtube-dl:
    command: bin/youtube-dl
    plugs:
      - home
      - network
    environment:
      # WORKAROUND: Allow youtube-dl to use UTF-8 filenames
      LC_ALL: C.UTF-8

slots:
  dbus-daemon:
    interface: dbus
    bus: session
    name: com.github.unrud.VideoDownloader

environment:
  # WORKAROUND: .../pulseaudio subdirectory is missing from library path
  LD_LIBRARY_PATH: "${SNAP}/usr/lib/aarch64-linux-gnu/pulseaudio:${SNAP}/usr/lib/arm-linux-gnueabihf/pulseaudio:${SNAP}/usr/lib/i386-linux-gnu/pulseaudio:${SNAP}/usr/lib/powerpc64le-linux-gnu/pulseaudio:${SNAP}/usr/lib/s390x-linux-gnu/pulseaudio:${SNAP}/usr/lib/x86_64-linux-gnu/pulseaudio"

parts:
  youtube-dl:
    plugin: python
    python-version: python3
    source: https://yt-dl.org/downloads/2020.01.15/youtube-dl-2020.01.15.tar.gz
    source-checksum: sha256/556711f8dc827910096fd648d7ead051ddadb81b90ae4abdf0393ddf2d62d237
    stage-packages:
      # Missing optional dependencies mpv and phantomjs
      - atomicparsley
      - ffmpeg
      - libslang2  # required by ffmpeg
      - python3-pyxattr
      - rtmpdump
    override-build: |
      snapcraftctl build
      # WORKAROUND: Use correct python version
      sed -e '1c#!/usr/bin/env python3' -i "${SNAPCRAFT_PART_INSTALL}/bin/youtube-dl"

  pygobject:
    plugin: python
    python-packages:
      - pycairo
      - PyGObject
    build-packages:
      - libgirepository1.0-dev
      - libcairo2-dev
      - python3-dev
    stage-packages:
      - gir1.2-gtk-3.0

  video-downloader:
    plugin: meson
    source: .
    source-type: git
    # WORKAROUND: Fake installation location, to find dependencies when running
    meson-parameters: [--prefix=/snap/video-downloader/current/usr]
    build-packages:
      - gettext
      - librsvg2-bin
    stage-packages:
      - xdg-user-dirs
    override-pull: |
      snapcraftctl pull
      # WORKAROUND: Point icon to the correct location
      sed -e 's|Icon=com.github.unrud.VideoDownloader|Icon=/usr/share/icons/hicolor/scalable/apps/com.github.unrud.VideoDownloader.svg|' -i data/com.github.unrud.VideoDownloader.desktop.in
    override-build: |
      snapcraftctl build
      # WORKAROUND: Version is not extracted from AppStream
      snapcraftctl set-version "$(sed -n 's/^\s*VERSION\s*=\s*["'\'']\([^"'\'']*\)["'\''].*/\1/p' "${SNAPCRAFT_PART_INSTALL}/snap/video-downloader/current/usr/bin/video-downloader")"
      # WORKAROUND: Use correct python version
      sed -e '1c#!/usr/bin/env python3' -i "${SNAPCRAFT_PART_INSTALL}/snap/video-downloader/current/usr/bin/video-downloader"
    organize:
      snap/video-downloader/current/usr: usr
    parse-info: [usr/share/metainfo/com.github.unrud.VideoDownloader.appdata.xml]
